name: Cypress Tests

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        - name: Cache firebase emulators
          uses: actions/cache@v2
          with:
            path: ~/.cache/firebase/emulators
            key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICEACCOUNT }}
        with:
          start: npm run emulators, npm start
          working-directory: frontend
          wait-on: 'http://localhost:3000'
